services:
  # next-app:
  #   depends_on:
  #     - postgres
  #   container_name: next-app
  #   image: next-app
  #   restart: on-failure
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - ./node_modules:/app/node_modules
  #     - ./.next:/app/.next
  #   networks:
  #     - support-ticket-app

  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: on-failure
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/config/cutom-postgres.conf:/usr/local/share/postgresql/postgresql.conf
    networks:
      - support-ticket-app

# volumes:
#   node_modules:
#   build:

networks:
  support-ticket-app:
